### ISSUE TITLE
Log Measurements in PCR

### ISSUE THREAD

**Issue by eduardolfalcao** [nokia/TPMCourse#3]
Hi @iolivergithub 

Is there any setting we need to enable to let log measurements, for instance from IMA, to appear on PCRs?
I'm willing to perform container attestation based on applications loaded in OS boot time, and after boot time...

Thank you :)

**Comment by iolivergithub** [comment]
Hi,

for IMA...first you need to install IMA and enable it on the grub parameter
lines to the kernel.  IMA policies tend to write to PCR 10, though you can
change this if you write your own policies.
PCRs 0..7 are populated by the x86 firmware (see TCG x86 boot
documentation) - you have no control over what goes there, but if the TPM
is activated then you should get these automatically. Some later UEFI
systems write to 8,9 and 10 as well.

The UEFI event log should be available one of the securityfs directories
once the operating system is running
