### ISSUE TITLE
Docker image build errors

### ISSUE THREAD

**Issue by ericmiranda7** [nokia/TPMCourse#9]
At step 16, there are errors while building the Docker image:

`In file included from src/tss2-fapi/ifapi_curl.c:18:
src/tss2-fapi/ifapi_curl.c: In function 'ifapi_get_curl_buffer':
src/tss2-fapi/ifapi_curl.c:385:19: error: implicit declaration of function 'curl_url_strerror'; did you mean 'curl_multi_strerror'? [-Werror=implicit-function-declaration]
  385 |                   curl_url_strerror(url_rc));
      |                   ^~~~~~~~~~~~~~~~~
./src/util/log.h:55:49: note: in definition of macro 'LOG_ERROR'
   55 |                                      FORMAT, ## __VA_ARGS__)
      |                                                 ^~~~~~~~~~~
src/tss2-fapi/ifapi_curl.c:384:19: error: format '%s' expects argument of type 'char *', but argument 9 has type 'int' [-Werror=format=]
  384 |         LOG_ERROR("curl_url_set for CURUPART_URL failed: %s",
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  385 |                   curl_url_strerror(url_rc));
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~
      |                   |
      |                   int
./src/util/log.h:55:38: note: in definition of macro 'LOG_ERROR'
   55 |                                      FORMAT, ## __VA_ARGS__)
      |                                      ^~~~~~
src/tss2-fapi/ifapi_curl.c:384:59: note: format string is defined here
  384 |         LOG_ERROR("curl_url_set for CURUPART_URL failed: %s",
      |                                                          ~^
      |                                                           |
      |                                                           char *
      |                                                          %d
cc1: all warnings being treated as errors
make[1]: *** [Makefile:17330: src/tss2-fapi/libtss2_fapi_la-ifapi_curl.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/tpm2/tpm2-tss'
make: *** [Makefile:10458: all] Error 2
`

**Comment by iolivergithub** [comment]
Seems not to be occuring. The build does generate warnings (lots), but we see no errors with the current versions of the libraries and Alpine
